Self:
    Id: "1"
    ShownName: "peer1"
    Addr: "your ip:60000"

Members:
    Peers:
        - Id: "1"
          ShownName: "peer1"
          InAddr: "your ip:60000"
          OutAddr: "your ip:60000"

        - Id: "2"
          ShownName: "peer2"
          InAddr: "your ip2:60000"
          OutAddr: "your ip2:60000"
        